#include <QString>
#include <QSqlDatabase>
#include <QRegularExpression>
#include <QDateTime>
#include <QSqlQuery>
#include <QSqlError>
#include <QVector>
#include <QFile>
#include <QTextStream>
#include <QWebEngineView>
#include <QNetworkProxy>
#include <QDir>
#include <QTimer>
#include <QWebEngineProfile>
#include <QWebEngineSettings>
#include <QApplication>
#include <QWidget>
#include <QUrl>
#include <QObject>
#include <fstream>
#include <QThread>
#include <iostream>