#include <QString>
#include <QRegularExpression>
#include <QDateTime>
#include <libpq-fe.h>
#include <QVector>
#include <QFile>
#include <QTextStream>
#include <QWebEngineView>
#include <QNetworkProxy>
#include <QDir>
#include <QTimer>
#include <QElapsedTimer>
#include <QWebEngineProfile>
#include <QWebEngineSettings>
#include <QApplication>
#include <QWidget>
#include <QUrl>
#include <QObject>
#include <fstream>
#include <QThread>
#include <QNetworkAccessManager>
#include <QNetworkReply>
#include <QNetworkRequest>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <QJsonValue>
#include <iostream>